kharakhaichuk-ivan-keycloak:
  image: 'jboss/keycloak:latest'
  ports:
    - "127.0.0.1:9200:8080"
  environment:
    KEYCLOAK_USER: admin
    KEYCLOAK_PASSWORD: password
    DB_VENDOR: h2
    DB_USER: admin
    DB_PASSWORD: admin
    KEYCLOAK_IMPORT: "/tmp/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled"
  volumes:
    - ./keycloak/realms/realm-export.json:/tmp/realm-export.json
  container_name: kharakhaichuk-ivan-keycloak