version: '3.5'

services:
  kharakhaichuk-ivan-rest-service:
    image: 'kharakhaichuk-ivan-angular-rest-service:latest'
    ports:
      - "127.0.0.1:9000:8080"
    depends_on:
      - kharakhaichuk-ivan-db
    build:
      context: rest_service
    container_name: kharakhaichuk-ivan-rest-service

  kharakhaichuk-ivan-db:
    image: 'buildo/h2database'
    container_name: kharakhaichuk-ivan-db
    ports:
      - "8082:8084"
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d